package org.itmo.fuzzing.lect3;

import org.itmo.fuzzing.lect2.FunctionRunner;
import org.itmo.fuzzing.lect2.MutationFuzzer;

import java.util.*;
import java.time.Duration;
import java.util.function.BiPredicate;
import java.util.function.Consumer;
import java.util.stream.Collectors;

public class AdvancedMutationFuzzer extends MutationFuzzer {
    public List<String> seeds;
    public FuzzMutator mutator;
    public PowerSchedule schedule;
    public List<String> inputs;
    public List<Seed> population;
    private int seedIndex;
    private Random random;
    public Set<String> coveragesSeen = new TreeSet<>();
    private boolean recordInputs = true;


    /**
     * Constructor.
     *
     * @param seeds    - a list of (input) strings to mutate.
     * @param mutator  - the mutator to apply.
     * @param schedule - the power schedule to apply.
     */
    public AdvancedMutationFuzzer(
            List<String> seeds,
            FuzzMutator mutator,
            PowerSchedule schedule,
            int minMutations,
            int maxMutations
    ) {
        super(seeds, minMutations, maxMutations);
        if (minMutations < 0 || maxMutations < minMutations || maxMutations == Integer.MAX_VALUE) {
            throw new IllegalArgumentException("Require 0 <= minMutations <= maxMutations < Integer.MAX_VALUE");
        }
        this.seeds = seeds;
        this.mutator = mutator;
        this.schedule = schedule;
        this.inputs = new ArrayList<>();
        this.random = new Random();
        reset();
    }

    /**
     * Reset the initial population and seed index
     */
    public void reset() {
        this.population = seeds.stream()
                .map(Seed::new)
                .collect(Collectors.toList());
        this.seedIndex = 0;
    }

    /**
     * Returns an input generated by fuzzing a seed in the population
     */
    public String createCandidate() {
        Seed seed = schedule.choose(population);

        // Stacking: Apply multiple mutations to generate the candidate
        String candidate = seed.getData();
        int trials = random.nextInt(minMutations, maxMutations + 1);
        for (int i = 0; i < trials; i++) {
            candidate = mutator.mutate(candidate);
        }
        return candidate;
    }

    /**
     * Returns first each seed once and then generates new inputs
     */
    @Override
    public String fuzz() {
        String inp;
        if (seedIndex < seeds.size()) {
            // Still seeding
            inp = seeds.get(seedIndex);
            seedIndex++;
        } else {
            // Mutating
            inp = createCandidate();
        }

        if (recordInputs) {
            inputs.add(inp);
        }
        return inp;
    }

    @Override
    public String mutate(String input) {
        return mutator.mutate(input);
    }

    /**
     * Runs the target without changing the initial corpus (black-box mode).
     */
    public Object run(FunctionRunner runner, String input) {
        FunctionRunner.Tuple<Object, String> resultOutcome = runner.run(input);
        var result = resultOutcome.first;
        coveragesSeen.addAll(runner.coverage);
        return result;
    }

    public void fuzz(FunctionRunner runner, long trials) {
        fuzz(runner, trials, (input, result) -> false);
    }

    /**
     * Executes at most {@code trials} inputs, stopping when the supplied condition is met.
     * The condition receives the input and target result after {@link #run} has completed,
     * including any corpus or coverage updates performed by subclasses. The result may be null
     * when the target returns null or the runner catches an exception.
     *
     * <p>The budget and execution count apply to this invocation; the fuzzer is not reset.
     * A zero budget executes nothing and returns null input and result.</p>
     *
     * @throws IllegalArgumentException if trials is negative
     * @throws NullPointerException if runner or stopCondition is null
     */
    public FuzzingResult fuzz(FunctionRunner runner, long trials,
                            BiPredicate<String, Object> stopCondition) {
        return execute(runner, trials, null, stopCondition, 0, progress -> {});
    }

    /**
     * Runs until the condition matches or the time budget expires. Time is checked before
     * each execution; a running target is not interrupted. Progress is reported synchronously
     * after every {@code reportEvery} executions, and its cost counts towards the budget.
     * Zero time executes nothing. This invocation does not reset the fuzzer.
     */
    public FuzzingResult fuzz(FunctionRunner runner, Duration timeBudget,
                             BiPredicate<String, Object> stopCondition,
                             long reportEvery, Consumer<FuzzingProgress> observer) {
        Objects.requireNonNull(timeBudget, "timeBudget");
        if (timeBudget.isNegative() || reportEvery <= 0) {
            throw new IllegalArgumentException("timeBudget must be non-negative and reportEvery positive");
        }
        return execute(runner, Long.MAX_VALUE, timeBudget.toNanos(), stopCondition,
                reportEvery, Objects.requireNonNull(observer, "observer"));
    }

    private FuzzingResult execute(FunctionRunner runner, long trials, Long timeBudgetNanos,
                                 BiPredicate<String, Object> stopCondition,
                                 long reportEvery, Consumer<FuzzingProgress> observer) {
        Objects.requireNonNull(runner, "runner");
        Objects.requireNonNull(stopCondition, "stopCondition");
        if (trials < 0) {
            throw new IllegalArgumentException("trials must be non-negative");
        }

        String input = null;
        Object result = null;
        long startedAt = System.nanoTime();
        long executions = 0;
        for (long i = 0; i < trials; i++) {
            if (timeBudgetNanos != null && System.nanoTime() - startedAt >= timeBudgetNanos) {
                break;
            }
            input = fuzz();
            result = run(runner, input);
            executions++;
            boolean stopped = stopCondition.test(input, result);
            if (reportEvery > 0 && executions % reportEvery == 0) {
                observer.accept(new FuzzingProgress(executions, input, result,
                        Duration.ofNanos(System.nanoTime() - startedAt)));
            }
            if (stopped) {
                return new FuzzingResult(executions, input, result, true);
            }
        }
        return new FuzzingResult(executions, input, result, false);
    }

    /**
     * Last execution and count for one fuzzing invocation. {@code stoppedByCondition} is true
     * whenever the condition matched, including on the final budgeted execution.
     */
    public record FuzzingResult(long executions, String input, Object result,
                                boolean stoppedByCondition) {
    }

    public record FuzzingProgress(long executions, String input, Object result, Duration elapsed) {
    }

    /** Disables input history for long runs without affecting corpus admission. */
    public void setRecordInputs(boolean recordInputs) {
        this.recordInputs = recordInputs;
    }

    // Getters and setters
    public List<String> getInputs() {
        return inputs;
    }
}
